controllers:
    resource: ../src/Controller/
    type: annotation

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check
    methods: [POST]
